#!/bin/sh
#PBS -l  nodes=1:ppn=48 -q qmult
#PBS -l walltime=1000:00:00
#PBS -N hubvar
export PATH=/com/openmpi-1.2.5/bin:$PATH
export LD_LIBRARY_PATH=/com/intel/mkl/10.0.1.014/lib/em64t:/com/openmpi-1.2.5/lib:/com/intel/fce/10.1.017/lib:/com/gsl/1.15/lib


opmpi=/com/openmpi-1.2.5/lib
intel=/com/intel/fce/10.0.023/lib:/com/intel/cce/10.0.023/lib
export LD_LIBRARY_PATH=${opmpi}:${intel}:$LD_LIBRARY_PATH
cd $PBS_O_WORKDIR
export OMP_NUM_THREADS=48


#python hubble.py ../cases/Planck512/Planck512_withcorrections.yaml
#python hubble.py ../cases/Planck512/Planck512.yaml
#python hubble.py ../cases/Planck512/Planck512_nocorrections.yaml
#python hubble.py ../cases/Planck1024/Planck1024.yaml
python hubble.py ../cases/Planck1024_box1024/Planck1024_box1024_min_dist_80.yaml
#python hubble.py ../cases/sim16/sim16.yaml
#python hubble.py ../cases/CoDECS_LCDM/LCDM.yaml
#python hubble.py ../cases/CoDECS_EXP003/EXP003.yaml
#python hubble.py ../cases/CoDECS_EXP001/EXP001.yaml
#python hubble.py ../cases/CoDECS_EXP008e3/EXP008e3.yaml
#python hubble.py ../cases/CoDECS_SUGRA/SUGRA.yaml




echo "========= Job finished at `date` =========="
